name: 'Checking for updates for plugins'
description: 'checking for new versions'
inputs:
  working-directories:  # id of input
    description: 'Where to run command'
    required: true
    default: './'
  nativescript-versions:
    description: 'nativescript-versions for every project'
    required: true
    default: 'latest'
  is-android:
    description: ''
    required: false
    default: ''
outputs:
  pluginList: # id of output
    description: 'String with plugins versions'
  pluginsTestResult:
    description: 'String with a test result'
runs:
  using: 'node12'
  main: 'index.js'
